#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy STL file over 
cp greenhouse_R1_W4.stl constant/triSurface/greenhouse.stl
runApplication surfaceFeatures

runApplication blockMesh
runApplication checkMesh

runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite

mv log.checkMesh log.checkMesh-1
runParallel checkMesh

runParallel patchSummary
runParallel potentialFoam -writePhi -writep

runParallel postProcess -field Phi -funcs '( grad(Phi) mag(grad(Phi)) xaxis arc )'

#runApplication reconstructParMesh -constant
#runApplication reconstructPar -withZero

#------------------------------------------------------------------------------
