#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp greenhouse_R1_W4.stl constant/triSurface/greenhouse.stl
runApplication surfaceFeatures

runApplication blockMesh
runApplication checkMesh

runApplication snappyHexMesh -overwrite
mv log.checkMesh log.checkMesh-1
runApplication checkMesh

runApplication patchSummary

runApplication potentialFoam -writePhi -writep
runApplication postProcess -field Phi -funcs '( grad(Phi) mag(grad(Phi)) xaxis arc )'

#------------------------------------------------------------------------------
